services:
  web:
    image: ileady-api-gateway
    ports:
      - 3002:3002
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - IS_LOCAL=${IS_LOCAL}
      - JWT_SECRET=${JWT_SECRET}

      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}

      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

      - SQS_CUSTOMER_BOT_QUEUE_URL=${SQS_CUSTOMER_BOT_QUEUE_URL}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
